export const ADMIN_ROUTE= "/admin"
export const AUTH_ROUTE = "/login"
export const REGISTER_ROUTE = "/registration"
export const HOME_ROUTE = "/"
export const APPLICATION_FORM_ROUTE = "/application/add"